
[general]
	#The material blacklist of this module.
	materialBlacklist = []

[recipes]
	#The materials that should not have water industrial grinder recipes added.
	waterMaterialBlacklist = []
	#The materials that should not have mercury industrial grinder recipes added.
	mercuryMaterialBlacklist = []
	#The materials that should not have sodium persulfate	 industrial grinder recipes added.
	sodiumPersulfateMaterialBlacklist = []

