
#Configurations for material Sphalerite.
[general]
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#Is the storage block of this material small (2x2).
	isSmallStorageBlock = false
	#The module blacklist of this material.
	moduleBlacklist = []
	#Should items of this material have the enchanted glow.
	hasEffect = false
	#The model type of the material.
	modelType = "dust"
	#The color of this material.
	color = 9081961

[magneticraft]
	#The default byproduct material to output in Magneticraft's grinder.
	grinderByproduct = "minecraft:gravel"

[mekanism]
	#The default base to use in Mekanism's Combiner to recreate ores.
	oreBase = "minecraft:cobblestone"

